
export const CREATE_ANECDOTE = 'CREATE_ANECDOTE';

export const DELETE_ANECDOTE = 'DELETE_ANECDOTE';

export const VOTE_ANECDOTE = 'VOTE_ANECDOTE';

export const CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';

export const SET_FILTER = 'SET_FILTER';
